export default {
  RECEIVE_DATA: 'RECEIVE_DATA',
  RECEIVE_DATA_SUCCESS: 'RECEIVE_DATA_SUCCESS',
  RECEIVE_DATA_ERROR: 'RECEIVE_DATA_ERROR',

  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  UPDATE_DOCUMENT_SUCCESS: 'UPDATE_DOCUMENT_SUCCESS',
  UPDATE_DOCUMENT_ERROR: 'UPDATE_DOCUMENT_ERROR',

  DOCUMENT_ACCORDION: 'DOCUMENT_ACCORDION',
  CHAPTER_ACCORDION: 'CHAPTER_ACCORDION',
  VALIDATE_CHAPTER: 'VALIDATE_CHAPTER',
  VALIDATE_ARTICLE: 'VALIDATE_ARTICLE',
  SUBMIT_DOCUMENT: 'SUBMIT_DOCUMENT',
  SIDEBAR_VISIBLE: 'SIDEBAR_VISIBLE',

  GET_CONTRACTING_PARTY: 'GET_CONTRACTING_PARTY',
  GET_CONTRACTING_PARTY_SUCCESS: 'GET_CONTRACTING_PARTY_SUCCESS',
  GET_CONTRACTING_PARTY_ERROR: 'GET_CONTRACTING_PARTY_ERROR',

  UPDATE_CONTRACT_INFO: 'UPDATE_CONTRACT_INFO',

  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_DOCUMENT_EXPAND: 'TOGGLE_DOCUMENT_EXPAND',
  TOGGLE_GENERAL: 'TOGGLE_GENERAL',
  TOGGLE_COVER: 'TOGGLE_COVER',
  TOGGLE_CHAPTER: 'TOGGLE_CHAPTER',
  TOGGLE_ARTICLE: 'TOGGLE_ARTICLE',
  TOGGLE_ANNEX: 'TOGGLE_ANNEX',
};

export const DATE_FORMAT = 'DD/MM/YYYY';
